name: Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  Build:
    uses: microsoft/digitalworkplace-workflows/.github/workflows/build.yml@v2.1
    with:
     project-to-build: "src/Generator/Generator.csproj"
     project-to-test: "test/Generator.Tests/Generator.Tests.csproj"
     coverage-threshold: 100

  Pack:
    uses: microsoft/digitalworkplace-workflows/.github/workflows/pack.yml@v2.1
    with:
      project-to-pack: "src/Generator/Generator.csproj"

  Scan:
    uses: microsoft/digitalworkplace-workflows/.github/workflows/scan.yml@v2.1